name: Jimi Commit It

on:
  schedule:
    - cron: '5 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update timestamp
      run: |
        echo "Last update: $(date -u)" > timestamp.md
    - name: Update badge.json
      run: |
        echo "{\"schemaVersion\":1,\"label\":\"last commit\",\"message\":\"$(date -u +'%Y-%m-%d %H:%M UTC')\",\"color\":\"brightgreen\"}" > badge.json
    - name: Commit & Push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "github-actions"
        git add badge.json
        git commit -m "chore: update badge [skip ci]" || echo "No changes"
        git push

